app = "constellatione-rails"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  LOCAL_DOMAIN = "constellati.one"
  WEB_DOMAIN = "constellati.one"
  ALTERNATE_DOMAINS = "constellatione-rails.fly.dev"
  SMTP_DOMAIN = "mail.constellati.one"
  RAILS_ENV = "production"
  RAILS_LOG_TO_STDOUT = "enabled"
  WEB_CONCURRENCY = "3"
  REDIS_HOST = "constellatione-redis.internal"
  REDIS_PORT = "6379"
  S3_ENABLED=true
  S3_BUCKET="constellatione-media"
  S3_REGION="ap-northeast-1"
  S3_PROTOCOL="https"
  S3_HOSTNAME="s3-ap-northeast-1.amazonaws.com"
  S3_ALIAS_HOST="d1rwm3q2mm4wfd.cloudfront.net"
  PRIMARY_REGION="nrt"

[[statics]]
  guest_path = "/opt/mastodon/public"
  url_prefix = "/"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 3000

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    path = "/health"
    grace_period = "10s"
    interval = "10s"
    restart_limit = 0
    timeout = "2s"
